
import("//mojo/public/tools/bindings/mojom.gni")

mojom("jatter_mojom") {
  sources = [ "jatter.mojom" ]
}

source_set("jatter") {
  sources = [
    "jatter_authorization_impl.cc",
    "jatter_authorization_impl.h",
    "jatter_token_storage.cc",
    "jatter_token_storage.h",
    "jatter_firebase_client.cc",
    "jatter_firebase_client.h",
    "jatter_history_observer.cc",
    "jatter_history_observer.h",
    "jatter_profile_observer.cc",
    "jatter_profile_observer.h",
    "jatter_history_observer_service_factory.cc",
    "jatter_history_observer_service_factory.h",
  ]

  deps = [
    ":jatter_mojom",
    "//base",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",      
  ]

  public_deps = [
    ":jatter_mojom",
  ]
}